Replace gmaven-plugin with gmavenplus-plugin for Java 17
The gmaven-plugin:1.0 fails on Java 17 with:
InaccessibleObjectException: Unable to make
java.lang.String(char[],int,int,java.lang.Void)
accessible: module java.base does not opens java.lang

Replace with gmavenplus-plugin:3.0.2 + Groovy 4.0.15
which is compatible with Java 17's module system.

Issue-ID: SO-4145
Change-Id: Ie1777778f947adcbe2e80c7113ac4819dc7078ab
Signed-off-by: Fiete Ostkamp <fiete.ostkamp@telekom.de>